# Generated by Django 4.2.6 on 2023-10-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
